### ISSUE TITLE
Add a YAML file parser

### ISSUE THREAD

**Issue by anthonygardner** [anthonygardner/plant#5]
Simulations should be configurable using YAML file(s) provided in a `configs/` directory. I will breakout the YAML files if / when `sim.yml` gets too big. For now, I want to configure sims using a structure such as:

```yaml
globals:
- total time: 10 sec

integrator:
- type: rk4
- step size: 0.01 sec

agents:
- name: earth
   volume: 1
- name: moon
   volume: 0.25
```

I'll use this issue to track the addition of a YAML parser file (e.g, `src/core/parser.cc`). The implementation of the parsed config data will be handled in a separate thread.
